urls.py
from django.conf.urls import include, url
from django.contrib import admin
from .views.schema import schema_list, ioc_schema_list, tag_list, stix_schema_list
from .views.entity import db_list
from .views.graphdb import graphdb_view
from .views.visualize import visualize_view, vis_anonymize
from .views.delete import delete_view
from .views.export import export_relation, export_node, export_cluster, export_subcluster
from .views.stix_export import export_stix
from .views.cluster import cluster_list, cluster_view
from .views.subcluster import subcluster_list, subcluster_view
from .views.node import node_view, node_list
from .views.relation import relation_view, relation_list
from .views.ref import ref_view
from .views.ioc_import import import_ioc
from .views.ioc_export import export_ioc
from .tables import ClusterData, SubClusterData, NodeData, RelationData, IndexData, RelTemplateData


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', db_list),
    url(r'^db/$', db_list),
    url(r'^graphdb/$', graphdb_view),
    url(r'^schema/db/$', schema_list),
    url(r'^schema/openioc/$', ioc_schema_list),
    url(r'^schema/stix/$', stix_schema_list),
    url(r'^schema/tag/$', tag_list),
    url(r'^visualize/(?P<model>\w+)/(?P<id>\d+)$', visualize_view),
    url(r'^visualize/(?P<model>\w+)/$', visualize_view),
    url(r'^visualize/$', visualize_view),
    url(r'^vis_anonymize/(?P<model>\w+)/(?P<id>\d+)$', vis_anonymize),
    url(r'^vis_anonymize/(?P<model>\w+)/$', vis_anonymize),
    url(r'^vis_anonymize/$', vis_anonymize),
    url(r'^export/relation/(?P<model>\w+)/(?P<id>\d+)$', export_relation),
    url(r'^export/relation/$', export_relation),
    url(r'^export/node/(?P<model>\w+)/(?P<id>\d+)$', export_node),
    url(r'^export/node/$', export_node),
    url(r'^export/cluster/$', export_cluster),
    url(r'^export/subcluster/$', export_subcluster),
    url(r'^export/stix/(?P<model>\w+)/(?P<id>\d+)$', export_stix),
    url(r'^export/openioc/(?P<model>\w+)/(?P<id>\d+)$', export_ioc),
    url(r'^import/ioc/$', import_ioc),
    url(r'^delete/(?P<model>\w+)/(?P<id>\d+)$', delete_view),
    url(r'^delete/(?P<model>\w+)$', delete_view),
    url(r'^cluster/$', cluster_list),
    url(r'^cluster/data$', ClusterData.as_view(), name='cluster_data'),
    url(r'^cluster/(?P<id>\d+)$', cluster_view),
    url(r'^subcluster/$', subcluster_list),
    url(r'^subcluster/data$', SubClusterData.as_view(), name='subcluster_data'),
    url(r'^subcluster/(?P<id>\d+)$', subcluster_view),
    url(r'^index/data$', IndexData.as_view(), name='index_data'),
    url(r'^node/$', node_list),
    url(r'^node/(?P<id>\d+)$', node_view),
    url(r'^node/data$', NodeData.as_view(), name='node_data'),
    url(r'^relation/$', relation_list),
    url(r'^relation/(?P<id>\d+)$', relation_view),
    url(r'^relation/data$', RelationData.as_view(), name='relation_data'),
    url(r'^reltemplate/data$', RelTemplateData.as_view(), name='reltemplate_data'),
    #url(r'^ref/(?P<id>\d+)$', ref_view),
    url(r'^ref/(?P<model>\w+)/(?P<id>\d+)$', ref_view),
]

forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _
from django.forms.widgets import Select
from .models import *

input_formats = [
            '%Y/%m/%d %H:%M:%S',
            '%y/%m/%d %H:%M:%S',
            '%Y-%m-%d %H:%M:%S',
            '%Y/%m/%d %H:%M',
            '%y/%m/%d %H:%M',
            '%Y-%m-%d %H:%M',
            '%Y/%m/%d',
            '%y/%m/%d',
            '%Y-%m-%d',
        ]

class ClusterForm(forms.ModelForm):
    class Meta:
        model = Cluster
        fields = ["name", "description", "firstseen", "tag"]
    def __init__(self, *args, **kwargs):
        super(ClusterForm, self).__init__(*args, **kwargs)
        self.fields["firstseen"].input_formats = input_formats
        self.fields["tag"].required = False

class SubClusterForm(forms.ModelForm):
    class Meta:
        model = SubCluster
        fields = ["name", "description", "firstseen", "cluster", "tag"]
    def __init__(self, *args, **kwargs):
        super(SubClusterForm, self).__init__(*args, **kwargs)
        self.fields["cluster"].required = False
        self.fields["firstseen"].input_formats = input_formats
        self.fields["tag"].required = False

class IndexForm(forms.ModelForm):
    new_label = forms.CharField(max_length="200", required=False)
    new_key = forms.CharField(max_length="200", required=False)
    class Meta:
        model = NodeIndex
        fields = ["label", "new_label", "property_key", "new_key", "icon"]
    def __init__(self, *args, **kwargs):
        super(IndexForm, self).__init__(*args, **kwargs)
        self.fields["label"].required = False
        self.fields["property_key"].required = False
        self.fields["icon"].required = False
    def clean(self):
        label = self.cleaned_data["label"]
        l = self.cleaned_data["new_label"].strip()
        if not label and l:
            label, created = NodeLabel.objects.get_or_create(
                name = l
            )
            self.cleaned_data["label"] = label
        pk = self.cleaned_data["property_key"]
        k = self.cleaned_data["new_key"].strip()
        if not pk and k:
            key, created = PropertyKey.objects.get_or_create(
                name = k
            )
            self.cleaned_data["property_key"] = key
        return self.cleaned_data

class RelEditForm(forms.ModelForm):
    new_type = forms.CharField(max_length="200", required=False)
    class Meta:
        model = Relation
        fields = ["type", "new_type", "firstseen", "lastseen", "subcluster"]
    def clean(self):
        t = self.cleaned_data["new_type"].strip()
        if t:
            type, created = RelType.objects.get_or_create(
                name = t
            )
            self.cleaned_data["type"] = type
        return self.cleaned_data

class RelTemplateForm(forms.ModelForm):
    new_type = forms.CharField(max_length="200", required=False)
    class Meta:
        model = RelationTemplate
        fields = ["src_index", "dst_index", "type", "new_type"]
        labels = {
            'src_index': _('Source'),
            'dst_index': _('Destination'),
        }
    def __init__(self, *args, **kwargs):
        super(RelTemplateForm, self).__init__(*args, **kwargs)
        self.fields["src_index"].required = False
        self.fields["dst_index"].required = False
        self.fields["type"].required = False
    def clean(self):
        rt = self.cleaned_data["type"]
        t = self.cleaned_data["new_type"].strip()
        if not rt and t:
            type, created = RelType.objects.get_or_create(
                name = t
            )
            self.cleaned_data["type"] = type
        return self.cleaned_data

class TemplateForm(forms.Form):
    rel_template = forms.ModelChoiceField(
        queryset=RelationTemplate.objects.all().order_by("src_index"),
        label="Template"
    )
    src_value = forms.CharField(max_length="200", required=False, label="Source Value")
    dst_value = forms.CharField(max_length="200", required=False, label="Destination Value")
    postprocess = forms.BooleanField(required=False)

class RelCreateForm(forms.Form):
    src_index = forms.ModelChoiceField(
        queryset=NodeIndex.objects.all(),
        label="Src Index"
    )
    src_value = forms.CharField(max_length="200", required=False, label="Source Value")
    dst_index = forms.ModelChoiceField(
        queryset=NodeIndex.objects.all(),
        label="Dst Index",
        required=False,
    )
    dst_value = forms.CharField(max_length="200", required=False, label="Destination Value")
    reltype = forms.ModelChoiceField(
        queryset=RelType.objects.all(),
        label="Relation Type",
        required=False,
    )
    postprocess = forms.BooleanField(required=False)

class EntitySelectForm(forms.Form):
    entity = forms.ChoiceField(
        choices=(
            ("node","Node"),
            ("rel","Relation")
        )
    )
    id = forms.IntegerField(min_value=0, required=True)

class EntityForm(forms.Form):
    entity = forms.ChoiceField(
        choices=(
            ("node","Node"),
            ("rel","Relation")
        )
    )
    id = forms.IntegerField(min_value=0, required=False)
    key = forms.ModelChoiceField(queryset=PropertyKey.objects.all().order_by("name"), required=False, label="Property Key")
    new_key = forms.CharField(max_length="200", required=False, label="New Key")
    value = forms.CharField(max_length="200", required=False, label="Property Value")
    subcluster = forms.ModelMultipleChoiceField(queryset=SubCluster.objects.all().order_by("name"))
    postprocess = forms.BooleanField(required=False)
    def __init__(self, *args, **kwargs):
        super(EntityForm, self).__init__(*args, **kwargs)
        self.fields["subcluster"].required = False
    def clean(self):
        key = self.cleaned_data["key"]
        nk = self.cleaned_data["new_key"].strip()
        if not key and nk:
            pk, created = PropertyKey.objects.get_or_create(
                name = nk
            )
            self.cleaned_data["key"] = pk
        return self.cleaned_data

class NodeForm(forms.ModelForm):
    class Meta:
        model = Node
        fields = ["index", "value", "subcluster"]

class PropertyForm(forms.ModelForm):
    new_key = forms.CharField(max_length="200", required=False, label="New Key")
    class Meta:
        model = Property
        fields = ["key", "new_key", "value"]
    def __init__(self, *args, **kwargs):
        super(PropertyForm, self).__init__(*args, **kwargs)
        self.fields["key"].required = False
        self.fields["value"].required = False
    def clean(self):
        key = self.cleaned_data["key"]
        nk = self.cleaned_data["new_key"].strip()
        if not key and nk:
            pk, created = PropertyKey.objects.get_or_create(
                name = nk
            )
            self.cleaned_data["key"] = pk
        return self.cleaned_data

class UploadFileForm(forms.Form):
    file = forms.FileField()
    postprocess = forms.BooleanField(required=False)

class IOCTermForm(forms.ModelForm):
    iocterm = forms.ModelChoiceField(
        queryset=IOCTerm.objects.all(),
        label="OpenIOC Term",
        required=False,
    )
    class Meta:
        model = IOCTerm
        fields = ["iocterm", "text", "index", "allow_import", "allow_export"]
    def __init__(self, *args, **kwargs):
        super(IOCTermForm, self).__init__(*args, **kwargs)
        self.fields["text"].label = "New IOC Term"
        self.fields["text"].required = False
        self.fields["allow_import"].widget = Select(choices=((0,"False"),(1,"True")))
        self.fields["allow_export"].widget = Select(choices=((0,"False"),(1,"True")))
    def clean(self):
        ioc = self.cleaned_data["iocterm"]
        text = self.cleaned_data["text"].strip()
        if not ioc and text:
            ioc, created = IOCTerm.objects.get_or_create(
                text = text
            )
            self.cleaned_data["iocterm"] = ioc
        return self.cleaned_data

class CybObjForm(forms.ModelForm):
    cybobj = forms.ModelChoiceField(
        queryset=CybOXObj.objects.all(),
        label="Cybox Object",
        required=False,
    )
    class Meta:
        model = CybOXObj
        fields = ["cybobj", "name", "index", "allow_import", "allow_export"]
    def __init__(self, *args, **kwargs):
        super(CybObjForm, self).__init__(*args, **kwargs)
        self.fields["name"].label = "New Object"
        self.fields["name"].required = False
        self.fields["allow_import"].widget = Select(choices=((0,"False"),(1,"True")))
        self.fields["allow_export"].widget = Select(choices=((0,"False"),(1,"True")))

class TagForm(forms.ModelForm):
    new_key = forms.CharField(max_length="200", required=False, label="New Key")
    class Meta:
        model = Tag
        fields = ["key", "new_key", "value"]
    def __init__(self, *args, **kwargs):
        super(TagForm, self).__init__(*args, **kwargs)
        self.fields["key"].required = False
        self.fields["value"].required = False
    def clean(self):
        key = self.cleaned_data["key"]
        nk = self.cleaned_data["new_key"].strip()
        if not key and nk:
            pk, created = PropertyKey.objects.get_or_create(
                name = nk
            )
            self.cleaned_data["key"] = pk
        return self.cleaned_data

views/cluster.py
from django.shortcuts import redirect, render
from django.contrib import messages 

from ..models import *
from ..forms import *
from .graph import graph_init
from .db import push_all_to_graph
from .subcluster import create_subcluster
from .ioc_import import import_ioc, pre_import_ioc
from .stix_import import pre_import_stix
from .csv_import import import_cluster

def cluster_list(request):
    form = ClusterForm()
    iform = UploadFileForm()
    if request.method == "POST":
        if "create" in request.POST:
            form = ClusterForm(request.POST)
            if form.is_valid():
                name = form.cleaned_data["name"].strip()
                description = form.cleaned_data["description"]
                firstseen = form.cleaned_data["firstseen"]
                tag = form.cleaned_data["tag"]
                c, created = Cluster.objects.get_or_create(
                    name = name
                )
                if c and created:
                    if description:
                        c.description = description
                    if firstseen:
                        c.firstseen = firstseen
                    if tag:
                        c.tag = tag
                    c.save()
        elif "delete" in request.POST:
            return redirect("/delete/cluster")
        elif "import_csv" in request.POST:
            iform = UploadFileForm(request.POST, request.FILES)
            if iform.is_valid():
                try:
                    import_cluster(request.FILES['file'])
                except Exception as e:
                    messages.add_message(request, messages.WARNING, str(type(e)) + ": "+ str(e))
        elif "import_ioc" in request.POST:
            iform = UploadFileForm(request.POST, request.FILES)
            if iform.is_valid():
                sc = None
                try:
                    sc = pre_import_ioc(request.FILES['file'])
                except Exception as e:
                    messages.add_message(request, messages.WARNING, str(type(e)) + ": "+ str(e))
                if sc:
                    context = {
                        "subcluster":sc,
                        "cluster":sc["cluster"],
                        "node":sc["node"],
                    }
                    return render(request, "import_view.html", context)

    c = {
       "form":form,
       "iform":iform,
    }
    return render(request, "cluster_list.html", c)


def cluster_view(request, id):
    graph = graph_init()
    cluster = Cluster.objects.get(id=id)
    subcluster = SubCluster.objects.filter(cluster=cluster)
    nodes = Node.objects.filter(subcluster__cluster=cluster).distinct()
    relations = Relation.objects.filter(subcluster__cluster=cluster).distinct()
    form = ClusterForm(instance=cluster)
    scform = SubClusterForm()
    iform = UploadFileForm()
    if request.method == "POST":
        if "update" in request.POST:
            form = ClusterForm(request.POST)
            if form.is_valid():
                name = form.cleaned_data["name"].strip()
                if name and not name == cluster.name:
                    cluster.name = name
                description = form.cleaned_data["description"]
                cluster.description = description
                firstseen = form.cleaned_data["firstseen"]
                if firstseen:
                    cluster.firstseen = firstseen
                tag = form.cleaned_data["tag"]
                cluster.tag.clear()
                cluster.tag = tag
                cluster.save()
        elif "delete" in request.POST:
            return redirect("/delete/cluster/" + id)
        elif "push_all" in request.POST:
            push_all_to_graph(nodes, relations, graph)
        elif "create_subcluster" in request.POST:
            scform = SubClusterForm(request.POST)
            if scform.is_valid():
                s = create_subcluster(scform)
                if s:
                    s.cluster.add(cluster)
        elif "import_ioc" in request.POST:
            iform = UploadFileForm(request.POST, request.FILES)
            if iform.is_valid():
                sc = pre_import_ioc(request.FILES['file'])
                if sc:
                    context = {
                        "subcluster":sc,
                        "cluster":cluster,
                        "node":sc["node"],
                    }
                    return render(request, "import_view.html", context)
        elif "import_stix" in request.POST:
            iform = UploadFileForm(request.POST, request.FILES)
            if iform.is_valid():
                sc = pre_import_stix(request.FILES['file'], cluster=cluster)
                if sc:
                    context = {
                        "subcluster":sc,
                        "cluster":sc["cluster"],
                        "node":sc["node"],
                    }
                    return render(request, "import_stix.html", context)
    print form
    c = {
        "form":form,
        "scform":scform,
        "iform":iform,
        "cluster":cluster,
        "subcluster":subcluster,
        "nodes":nodes,
        "relations":relations,
        "model":"cluster",
    }
    return render(request, "cluster_view.html", c)

templates/cluster_view.html
{% extends "base.html" %}

{% block title %}
<title>{{model|capfirst}}</title>
{% endblock %}

{% block jquery %}
<script>
$(document).ready(
        function(){
       		$(".cluster_form").toggle();
       		$(".subcluster_form").toggle();
		$('.btn-toggle').click(function(){
			if($(this).attr("value")=="cluster_form"){
       				$(".cluster_form").toggle();
	       		};
			if($(this).attr("value")=="subcluster_form"){
       				$(".subcluster_form").toggle();
	       		};
	       	});
                $('a[data-toggle="tab"]').on( 'shown.bs.tab', function (e) {
                    $.fn.dataTable.tables( {visible: true, api: true} ).columns.adjust();
                } );
		$('#subcluster_table').dataTable({
                    "processing":true,
                    "serverSide":true,
                    "ajax": {
                        "url": "/subcluster/data",
                        "data": {'cluster':{{cluster.id}}},
                    },
                    "order":[0, 'desc'],
                });
		$('#node_table').dataTable({
                    "processing":true,
                    "serverSide":true,
                    "ajax": {
                        "url": "/node/data",
                        "data": {'cluster':{{cluster.id}}},
                    },
                    "order":[0, 'desc'],
                });
		$('#relation_table').dataTable({
                    "processing":true,
                    "serverSide":true,
                    "ajax": {
                        "url": "/relation/data",
                        "data": {'cluster':{{cluster.id}}},
                    },
                    "order":[0, 'desc'],
                });
                //$('#id_firstseen').datetimepicker({
                //        format:'Y-m-d H:i'
                //});
                function table_btn(b){
                        if(b.hasClass("node_id")){
                                $("select#id_entity").val("node");
                        	$("input#id_id").val(b.attr("value"));
                        }else if(b.hasClass("rel_id")){
                                $("select#id_entity").val("rel");
                        	$("input#id_id").val(b.attr("value"));
                        };
                };
                $('tbody').on('click', '.btn', function (e) {
                        table_btn($(this));
                });
	}
);
</script>
{% endblock%}

{% block container %}

<div class="modal" id="cluster_form" role="dialog">
<div class="modal-dialog"><div class="modal-content">
<div class="modal-header">
<button type="button" class="close" data-dismiss="modal">&times;</button>
<h4 class="modal-title">Create Node/Relation on Local DB</h4>
</div>
<div class="modal-body">
<form method=post>{% csrf_token %}
<table class="table table-condensed">
<tr><th class="col-sm-1"></th><td class="col-sm-3"></td></tr>
{{form.as_table}}
</table>
<input class="btn btn-primary btn-sm" type="submit" name="update" value="Update">
<input class="btn btn-danger btn-sm" type="submit" name="delete" value="Delete">
<input class="btn btn-info btn-sm" type="submit" name="push_all" value="Push All">
</form>
</div><!--/.modal-body-->
</div><!--/.modal-content-->
</div><!--/.modal-dialog-->
</div><!--/.modal-->

<div class="modal" id="import_form" role="dialog">
<div class="modal-dialog"><div class="modal-content">
<div class="modal-header">
<button type="button" class="close" data-dismiss="modal">&times;</button>
<h4 class="modal-title">Import/Export</h4>
</div>
<div class="modal-body">
<a class="btn btn-info btn-md " href="/export/node/cluster/{{cluster.id}}">Export Node</a>
<a class="btn btn-info btn-md " href="/export/relation/cluster/{{cluster.id}}">Export Relation</a>
<!--<a class="btn btn-info btn-md " href="/export/stix/cluster/{{cluster.id}}">Export STIX</a>-->
<hr>
<form enctype="multipart/form-data" method=post>{% csrf_token %}
<table >
{{iform.as_table}}
</table>
<br>
<input class="btn btn-warning btn-md" type="submit" name="import_ioc" value="Import IOC">
<input class="btn btn-warning btn-md" type="submit" name="import_stix" value="Import STIX">
</form>
</div><!--/.modal-body-->
</div><!--/.modal-content-->
</div><!--/.modal-dialog-->
</div><!--/.modal-->

<div class="col-md-12">

<div id="accordion">
<div class="panel panel-primary">

<div class="panel-heading">
<a data-toggle="collapse" data-parent="#accordion" href="#collapse1" style="color:white">
{{model|capfirst}}
</a>
</div>
<div id="collapse1" class="panel-collapse collapse in">
<div class="panel-body">
<div class="col-md-6">
<table class="table table-condensed">
<tr><th class="col-md-3">ID</th><td><a class="btn btn-primary btn-sm" href="/{{model}}/{{cluster.id}}">{{cluster.id}}</a></td></tr>
<tr><th>Name</th><td>{{cluster.name}}</td></tr>
<tr><th>Created</th><td>{{cluster.created}}</td></tr>
<tr><th>Modified</th><td>{{cluster.modified}}</td></tr>
<tr><th>First seen</th><td>{{cluster.firstseen}}</td></tr>
<tr><th>Tag</th>
<td>
{% for t in cluster.tag.all %}
{{t}}<br>
{% endfor %}
</td></tr>
</table>
<a class="btn btn-info" data-toggle="modal" href="#cluster_form">Edit</a>
<a class="btn btn-warning" data-toggle="modal" href="#import_form">Import/Export</a>
<a class="btn btn-default btn-md " href="/visualize/cluster/{{cluster.id}}">Visualize</a>
<a class="btn btn-default btn-md " href="/vis_anonymize/cluster/{{cluster.id}}">Visualize(mask)</a>
</div>
<div class="col-md-6">
<table class="table table-condensed">
<tr><th>Description</th></tr>
<tr><td><pre>{{cluster.description}}</pre></td></tr>
</table>
</div>
</div><!--/.panel-body-->
</div>

<div class="panel-heading">
<a data-toggle="collapse" data-parent="#accordion" href="#collapse2" style="color:white">
Create SubCluster
</a>
</div>
<div id="collapse2" class="panel-collapse collapse">
<div class="panel-body">
<form method=post>{% csrf_token %}
<table class="table table-condensed">
<tr><th class="col-md-1"></th><td class="col-md-3"></td></tr>
{{scform.as_table}}
</table>
<input class="btn btn-info" type="submit" name="create_subcluster" value="Create">
</form>
</div><!--/.panel-body-->
</div>
</div><!--/.panel-->
</div>

<div id="list" class="col-md-12">

<ul class="nav nav-pills">
  <li class="active" ><a data-toggle="tab" href="#subcluster">SubCluster({{subcluster|length}})</a></li>
  <li ><a data-toggle="tab" href="#node">Node({{nodes|length}})</a></li>
  <li ><a data-toggle="tab" href="#relation">Relation({{relations|length}})</a></li>
</ul>

<div class="tab-content">

<div class="tab-pane active" id="subcluster" >
<table id="subcluster_table" class="table table-condensed table-stripe table-hover display" width="100%">

<thead><tr>
<th class="col-md-1">ID</th>
<th class="col-md-3">Name</th>
<th class="col-md-2">Cluster</th>
<th class="col-md-4">Description</th>
<th class="col-md-2">Firstseen</th>
</tr></thead>
</table>
</div><!--/#subcluster-->

<div class="tab-pane " id="node" >
<table id="node_table" class="table table-condensed table-stripe table-hover display" width="100%">

<thead><tr>
<th class="col-sm-1">ID</th>
<th class="col-sm-1">Ref</th>
<th class="col-sm-2">Created</th>
<th class="col-sm-2">Index</th>
<th class="col-sm-2">Value</th>
<th class="col-sm-4">SubCluster/Cluster</th>
</tr></thead>
</table>

</div><!--/#node-->

<div class="tab-pane" id="relation" >

<table id="relation_table" class="table table-condensed table-stripe table-hover display" width="100%">
<thead>
<th class="col-sm-1">ID</th>
<th class="col-sm-1">Ref</th>
<th class="col-sm-2">First seen</th>
<th class="col-sm-0.5"></th>
<th class="col-sm-3">Src Node</th>
<th class="col-sm-1">Relation</th>
<th class="col-sm-0.5"></th>
<th class="col-sm-3">Dst node</th>
</thead>
</table>

</div><!--/#relation-->

</div><!--/tab-content-->

</div><!--col-md-8-->

{% endblock %}

templates/tag_list.html
{% extends "base.html" %}

{% block title %}
<title>Tag</title>
{% endblock %}

{% block jquery %}
<script>
$(document).ready(
	function(){
                $('#index_table').DataTable({"order":[0, 'desc']});
                $('#reltemplate_table').DataTable({"order":[0, 'desc']});
                $('#iocterm_table').DataTable({"order":[0, 'desc']});
		//$('#id_firstseen').datetimepicker({
		//	format:'Y-m-d H:i'
		//});
	}
);
</script>
{% endblock%}

{% block container %}

<div class="col-md-5" id="form" >

{% if tform %}
<div class="panel panel-primary">
<div class="panel-heading">Create Tag</div>
<div class="panel-body">
<form method=post>{% csrf_token %}
<table class="table table-condensed">
<tr><th class="col-sm-1"></th><td class="col-sm-3"></td></tr>
{{tform.as_table}}
</table>
<input class="btn btn-primary btn-md" type="submit" name="create_tag" value="Create">
</form>
</div><!--/.panel-body-->
</div><!--/.panel-->
{% endif %}

</div><!--/#form-->

<div id="list" class="col-md-7">

<div id="tag" >
<table id="index_table" class="table table-condensed table-hover table-striped">

<thead><tr >
<th class="col-md-1">ID</th>
<th class="col-md-5">Key</th>
<th class="col-md-5">Value</th>
<th class="col-md-1">Del</th>
</tr></thead>

<tbody>
{% for t in tag %}
<tr>
<td>
{{t.id}}
</td>
<td>{{t.key}}</td>
<td>{{t.value}}</td>
<td><a class="btn btn-default btn-xs" href="/delete/tag/{{t.id}}?next=/schema/tag/">x</a></td>
</tr>
{% endfor %}
</tbody>

</table>

</div><!--/tag-->

</div><!--/#list-->

{% endblock %}